radar = None
us = None
them = None
explore_map = False
rockets_queue = {}
rocket_landings = []
rockets_waiting = {}
NUM_ROCKET_HEALERS = 1
NUM_ROCKET_WORKERS = 3
NUM_ROCKET_RANGERS = 3
NUM_ROCKET_MAGES = 1
ROCKET_DISTANCE = 10
ROCKET_ERROR = 2
TURNS_TIL_LAUNCH = 5
ROCKET_HEALTH_MIN = 50
ROCKET_HEALTH_MIN_IF_ALMOST_FULL = 100
REPLICATE_UNTIL = 7
PRODUCE_HEALER_CONSTANT = -30
MAX_WORKERS = 50
BEGINNING_WORKER_LIMIT = 7
MAX_FACTORIES = 6

income = 0
prev_karb_amount = 0
on_mars = False

pathToEnemy = {}
pathToEnemyMars = {}
updatePath = {}
updatePathMars = {}
pathsToKarb ={}
workers_factory_duty = {}
asteroid_pattern = None
earth_width = 0
mars_width = 0
earth_height = 0
mars_height = 0
wtime = 0
rtime = 0
ftime = 0

